### ISSUE TITLE
Documenting some errors I ran into for others

### ISSUE THREAD

**Issue by Sell24** [amrshawky/laravel-currency#1]
This isn't so much an issue but just to help others that may use this package and run into the same problems I did.

1. First you cannot directly use Currency. So, 

` $rates = Currency::rates()->latest()->get();`

will result in "Non-static method AmrShawky\Currency\Currency::rates() should not be called statically".  Instead you must instantiate Currency then use it like:

` $rates = (new Currency())->rates()->latest()->get();`

Maybe consider modifying the readme?

2. If you are testing the package on localhost you _**may**_ run into an issue where nothing is returned. In digging into the code, since the package uses Guzzle, not having a valid cert will result in this error:

`GuzzleHttp\Exception\RequestException cURL error 60: SSL certificate problem: unable to get local issuer certificate `

So you have two choices, go through the steps to install a valid certificate on your system (SO helps here) or modify the code to disable SSL certificate validation. You can do this as follows in the CurrencyRate.php file constructor:

` $this->client = $client ?? new Client(['verify' => false ]);`

Similarly you would need to do this in CurrencyConversion.php if you use that. Of course do not do this in production.

HTH others using this package.

**Comment by amrshawky** [comment]
> 1. First you cannot directly use Currency. So,
$rates = Currency::rates()->latest()->get();

Using currency directly is absolutely fine and working with no issues, upon installation Laravel will auto discover the package and register the alias:

```
"extra": {
        "laravel": {
            "providers": [
                "AmrShawky\\Currency\\CurrencyServiceProvider"
            ],
            "aliases": {
                "Currency": "AmrShawky\\Currency\\CurrencyFacade"
            }
        }
    },
```

so if auto discovery is disabled then you've to manually register the service provider and alias in `config/app.php`

> 2. If you are testing the package on localhost you may run into an issue where nothing is returned. In digging into the code, since the package uses Guzzle, not having a valid cert will result in this error:

Will add that in the next update.

Thanks.

**Comment by Sell24** [comment]
Thank you for your reply. I am not sure why the auto discovery would not have worked. This is a new Laravel 8 install and I don't see it in the app.php file. And I installed it using composer. In looking at the package.json file, I see this entry

`    "extra": {
        "laravel": {
            "dont-discover": []
        }
    },`

Other than that, is there any other way you know of that would prevent this package from being discovered?

**Comment by Sell24** [comment]
So I installed a fresh version of Laravel 8 using:
 
`composer create-project laravel/laravel  my-project`

and installed your package as documented:

`composer require amrshawky/laravel-currency` 

and it gave the following results: 

```
Using version ^2.0 for amrshawky/laravel-currency
./composer.json has been updated
Running composer update amrshawky/laravel-currency
Loading composer repositories with package information
Updating dependencies
Lock file operations: 1 install, 0 updates, 0 removals
  - Locking amrshawky/laravel-currency (2.0.0)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing amrshawky/laravel-currency (2.0.0): Extracting archive
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi
Discovered Package: amrshawky/laravel-currency
Discovered Package: facade/ignition
Discovered Package: fideloper/proxy
Discovered Package: fruitcake/laravel-cors
Discovered Package: laravel/sail
Discovered Package: laravel/tinker
Discovered Package: nesbot/carbon
Discovered Package: nunomaduro/collision
Package manifest generated successfully.
74 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
```
but it did not add the class or alias to app.php although I do see the following entries in composer.lock

```
           "extra": {
                "laravel": {
                    "providers": [
                        "AmrShawky\\Currency\\CurrencyServiceProvider"
                    ],
                    "aliases": {
                        "Currency": "AmrShawky\\Currency\\CurrencyFacade"
                    }
                }
            },
            "autoload": {
                "psr-4": {
                    "AmrShawky\\Currency\\": "src"
                }
            },
```

Not sure why it is not working...

**Comment by amrshawky** [comment]
Looks like you're importing the class with the `use` statement, remove it and it should work.
