### ISSUE TITLE
Converted amount is being rounded up.

### ISSUE THREAD

**Issue by chard1988** [amrshawky/laravel-currency#11]
I used this package for a project and noticed that the converted amount is being rounded up.

![image](https://user-images.githubusercontent.com/24698545/179896102-03ccbc52-c72e-4bdd-944f-3b56aeb22c7b.png)

![image](https://user-images.githubusercontent.com/24698545/179896131-263d8a54-d1e7-4ed0-b1e9-d38f38840c6c.png)

`function monetize($amount) {

        // Get current location
        $ip = request()->ip();
        $geoData = geoip($ip);

        // Get currency symbol
        $dbCurrency = Currency::where('code', $geoData['currency'])->first();

        // Strip "," symbol
        $stripped = str_replace(',', '', number_format($amount/100, 2));

        if ($amount != 0) {
            $retval = CurrencyConverter::convert()
                ->from('PHP')
                ->to($geoData['currency'])
                ->amount($stripped)
                ->round(2)
                ->get();
        } else {
            $retval = number_format($amount/100, 2);
        }

        $retval =  $dbCurrency->symbol . ' ' . $retval;
        $decimal = substr($retval, strpos($retval, '.') + 1);
        $cur = strtok($retval, '.');

        return __(':cur<small>.:decimal</small>', ['cur' => $cur, 'decimal' => $decimal]);
    }`

is there any way to prevent this from happening?

Kind regards,

**Comment by amrshawky** [comment]
Remove the `->round(2)` from your call
