### ISSUE TITLE
I tried converting from USD to ETH but got a weird error

### ISSUE THREAD

**Issue by ebuka-odih** [amrshawky/laravel-currency#13]
This is the function below

public function showRate()
    {
        $currency = Currency::convert()
            ->from('USD')
            ->to('ETH')
            ->source('crypto')
            ->withoutVerifying()
            ->get();
        return floor($currency * $this->balance);
    }
    
    error: `A non-numeric value encountered`

**Comment by amrshawky** [comment]
The API does not support converting between fiat and crypto
