### ISSUE TITLE
Always returns null 

### ISSUE THREAD

**Issue by ahmetsabri** [amrshawky/laravel-currency#18]
`Currency::convert()
            ->from('USD')
            ->to($to)
            ->date($date)
            ->amount(1)
            ->round(2)
            ->get()`

Hi , the code above was working correctly bu last days started returning `null` , any idea ? 
thank you

**Comment by DipaliRadadiya** [comment]
`Currency::convert()->from('USD')->to('INR')->amount(1)->round(2)->get()
`
I have a same issue. any solution?
Thank you

**Comment by kevin-kirsten** [comment]
I believe this is not related to the package itself, this is because the source it uses [exchangerate.host](https://exchangerate.host/) is down now.

**Comment by amrshawky** [comment]
Hey guys, us the [throw](https://github.com/amrshawky/laravel-currency#throwing-exceptions) method to know what is the issue exactly

**Comment by CamilleScholtz** [comment]
exchangerate.host has been down for the past three days it seems...? Can I find any news about this anywhere?

**Comment by ahmetsabri** [comment]
now it works again the problem was related to  https://exchangerate.host 
thank you
