### ISSUE TITLE
Methods return "Null"

### ISSUE THREAD

**Issue by nMckenryan** [amrshawky/laravel-currency#3]
Hi, Thanks for compiling this package!

I'm running through a Laravel Tutorial that uses your package (https://www.youtube.com/watch?v=dHPcWbC62R4) but I'm running into a persistent issue.

I've tried to run the: 

```
Currency::convert()
        ->from('USD')
        ->to('EUR')
        ->get();
```

Method, but it returned 'null'. I've tried a combination of other methods, such as ->amount(40) but it yields the same result. 

I cloned and installed the 'master' repo that the tutorial is based on (Repo Here: https://github.com/codewithdary/laravel-currency-converter) and it yields the same problem. I've installed all the dependencies through composer but i seem to get the same result. 

I see that this package uses an API, just wanted to verify that this connection is still active?

**Comment by amrshawky** [comment]
Hi,

If you're using it on localhost, maybe it's a [TLS certificate issue](https://docs.guzzlephp.org/en/stable/faq.html?highlight=ssl#why-am-i-getting-an-ssl-verification-error), try chaining the `withoutVerifying()` method like this:

```php
Currency::convert()
        ->from('USD')
        ->to('EUR')
        ->withoutVerifying()
        ->get();
```

If this doesn't work, you always can [enable throwing Exceptions](https://github.com/amrshawky/laravel-currency#throwing-exceptions) to know what is exactly wrong.

Let me know how it goes.

**Comment by nMckenryan** [comment]
Thanks for getting back to me so quickly. Adding withoutVerifying() has fixed it. Fantastic! Thanks very much!
