### ISSUE TITLE
Package returns null

### ISSUE THREAD

**Issue by CodeCures** [amrshawky/laravel-currency#4]
i don't know what am doing wrong as this doesn't seem to work for me.
```php
use AmrShawky\LaravelCurrency\Facade\Currency;
Route::get('test', function(){
    dd(Currency::rates()->latest()->get());
});
```
i don't suppose there is any configuration file to publish because there was no provision for that.
I have re-installed the package but still nothing.

**Comment by amrshawky** [comment]
Enable [Throwing Exceptions](https://github.com/amrshawky/laravel-currency#throwing-exceptions) and if it's a [certificate issue](https://docs.guzzlephp.org/en/stable/faq.html?highlight=ssl#why-am-i-getting-an-ssl-verification-error) you can chain the [withoutVerfiying method](https://github.com/amrshawky/laravel-currency#other-methods)

**Comment by CodeCures** [comment]
> Enable [Throwing Exceptions](https://github.com/amrshawky/laravel-currency#throwing-exceptions) and if it's a [certificate issue](https://docs.guzzlephp.org/en/stable/faq.html?highlight=ssl#why-am-i-getting-an-ssl-verification-error) you can chain the [withoutVerfiying method](https://github.com/amrshawky/laravel-currency#other-methods)

that was helpful... thanks
