### ISSUE TITLE
Returning null on convert

### ISSUE THREAD

**Issue by Thotsuya** [amrshawky/laravel-currency#9]
Today, every time I convert any amount it returns null 

AmrShawky\LaravelCurrency\Facade\Currency::convert()->from('USD')->to('EUR')->amount(2)->get();

AmrShawky\LaravelCurrency\Facade\Currency::convert()->from('USD')->to('HNL')->amount(1)->get();

Both return null

**Comment by fdelvals** [comment]
same problem here..

**Comment by dimifontaine** [comment]
I have the same problem but looks it's coming from the underlying api (the server is down at the time I'm writing this).

**Comment by fdelvals** [comment]
> I have the same problem but looks it's coming from the underlying api (the server is down at the time I'm writing this).

now it is working... looks like a temporal issue

**Comment by amrshawky** [comment]
Thank you for reporting this guys, you always can [enable throwing Exceptions](https://github.com/amrshawky/laravel-currency#throwing-exceptions) to know what is exactly wrong.
